# Generated by Django 4.1.5 on 2023-01-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Gênero', models.CharField(max_length=100)),
                ('Estado_Civil', models.CharField(max_length=100)),
                ('Data_Nascimento', models.DateField(max_length=100)),
                ('Naturalidade', models.CharField(max_length=100)),
                ('Profissão', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100)),
                ('Religião', models.CharField(max_length=100)),
                ('Telefone', models.CharField(blank=True, max_length=100)),
                ('Mãe', models.CharField(max_length=100)),
                ('Paciente', models.CharField(max_length=100)),
                ('Cep', models.CharField(max_length=100)),
                ('Rua_avenida', models.CharField(max_length=100)),
                ('Número', models.CharField(max_length=100)),
                ('Complemento', models.CharField(max_length=100)),
                ('Bairro', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
                ('Convênio', models.CharField(max_length=100)),
                ('Plano', models.CharField(max_length=100)),
                ('Cartão', models.CharField(max_length=100)),
                ('Data_vencimento', models.DateField(max_length=100)),
            ],
        ),
    ]
