# Generated by Django 4.1.5 on 2023-01-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Paciente',
            new_name='Pai',
        ),
    ]
