# Generated by Django 4.1.5 on 2023-01-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_paciente_paciente_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Estado_Civil',
            field=models.CharField(choices=[('C', 'Casado'), ('D', 'Divorciado'), ('S', 'Solteiro'), ('V', 'Viúvo')], max_length=1, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Gênero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
