# Generated by Django 4.1.5 on 2023-01-31 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_paciente_estado_civil_alter_paciente_gênero'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Estado_Nascimento',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Cartão',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Data_vencimento',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Gênero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Mãe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Pai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Plano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Profissão',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Religião',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Telefone',
            field=models.CharField(max_length=100),
        ),
    ]
