# Generated by Django 4.1.5 on 2023-02-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_paciente_estado_nascimento_alter_paciente_cartão_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Estado_Civil',
            field=models.CharField(max_length=100, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Estado_Nascimento',
            field=models.CharField(max_length=100, verbose_name='Estado Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Gênero',
            field=models.CharField(max_length=100, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Naturalidade',
            field=models.CharField(max_length=100, verbose_name='Cidade Nascimento'),
        ),
    ]
