# Generated by Django 4.1.5 on 2023-03-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_paciente_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Data_Nascimento',
            field=models.DateField(),
        ),
    ]
